apiVersion: v1
kind: Service
metadata:
  namespace: default
  name: filepizza
spec:
  type: NodePort
  ports:
  - name: http
    port: 80
    protocol: TCP
  selector:
    app: filepizza
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  namespace: default
  name: filepizza
spec:
  replicas: 2
  minReadySeconds: 15
  template:
    metadata:
      labels:
        app: filepizza
    spec:
      dnsPolicy: ClusterFirst
      containers:
      - name: filepizza
        image: kern/filepizza:1.0.2
        ports:
        - containerPort: 80
        env:
        - name: FORCE_SSL
          value: "true"
